name: Reusable Workflow - ✅ Checks

on:
  workflow_call:
    inputs:
      upload-codecov:
        description: Upload code coverage
        type: boolean
        required: false
        default: false
    secrets:
      SONAR_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: false

jobs:
  checks:
    name: ✅ Tests & Sonar analysis
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: 🧪 Run tests
        run: mvn verify

      - name: 🔍 Upload coverage reports to Codecov
        if: ${{ inputs.upload-codecov }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: elieahd/randomizer

      - name: 🔍 Sonar code analysis
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 🔆 Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}